[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FileSelection"
version = "0.1"
authors = [
  { name="Shubhendu Shubham", email="s2.shubh2@gmail.com" },
]
description = "A small package to pick latest file using various methods"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = ""
"Bug Tracker" = ""